### ISSUE TITLE
Rendering long pages into multiple ones bug

### ISSUE THREAD

**Issue by tomhamiltonstubber** [tutorcruncher/pydf#3]
If we have one long page to render into multiple A4 pages, then we get the following:

![image](https://cloud.githubusercontent.com/assets/8955690/21639170/8c945a40-d266-11e6-8aef-bb2b0ce56853.png)

New to this version

**Comment by samuelcolvin** [comment]
Closed by using.

```css
tr {
  page-break-inside: avoid;
 }
```
